### ISSUE TITLE
Daily report "Plan" upcoming vacations bug 

### ISSUE THREAD

**Issue by Krupitski** [svanxxx/taskmanager#1]
Dear Svanxxx,

Could you please fix task manager online interface, so it will not show "wrench" symbols for weekend days between vacation airplane symbols in the Daily Report page plan section for upcoming vacation. Could you please show any other symbols to illustrate weekends? 

Sincerely yours,
Krupitski Sergei.
![capture](https://user-images.githubusercontent.com/45853598/49948755-1c543480-ff05-11e8-9516-984af0ab5dad.PNG)

**Comment by svanxxx** [comment]
Fixed in 7872345e6f88c2b808e37dc6ab220c0b0aeba55e
