### ISSUE TITLE
Sort items in the task "Assigned" combo-box in alphabetical order.

### ISSUE THREAD

**Issue by Krupitski** [svanxxx/taskmanager#2]
Hello Svan!

This is me again. I've found small not urgent issue. Could you please update sort order in the "Assigned" combo-box to be sorted in alphabetical order instead of some random order as it is now.

Thanks,
Sergei.
![image](https://user-images.githubusercontent.com/45853598/50221351-df28f000-03a5-11e9-90c4-3a1388debebc.png)

**Comment by svanxxx** [comment]
Fixed in 281c0a3ad779806fd1b4e40eceb85b0e51ef6f2f
