### ISSUE TITLE
Drawing bug in the task history tab 

### ISSUE THREAD

**Issue by Krupitski** [svanxxx/taskmanager#4]
Hello Sergei,

Please open "http://mps.resnet.com/taskmanagerbeta/showtask.aspx?ttid=58921" and go to history tab. If resolution of you display will be lesser than FHD, you will see screwed drawing as in the image example below.
![image](https://user-images.githubusercontent.com/45853598/50884237-5842c280-13fb-11e9-9c00-cdbbbb438cfb.png)

Thanks,
Krupitski Sergei.

**Comment by svanxxx** [comment]
closed
